# Generated by Django 4.0.2 on 2022-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='Нет рейтинга', max_digits=3, null=True),
        ),
    ]
